---
title: "CfP2"
format: 
   html: default
   docx: 
     link-citations: true
     reference-doc: docx/IDCC18.docx
   epub: default
   pdf: default
author:
   - name: Daniel Antal
     orcid: 0000-0003-1689-0557
editor: visual
toc: true
lang: en-GB
date: today
bibliography:
- bib/antal.bib
- bib/capsurveys.bib
- bib/eccch.bib
- bib/datagovernance.bib
- bib/datalicensing.bib
- bib/datalinking.bib
- bib/datapooling.bib
- bib/privatelyhelddata.bib
- bib/indicators.bib
- bib/administrativedata.bib
- bib/OpenMusE.bib
- bib/openmusicrepositories.bib
- bib/slovakia.bib
- bib/statreg.bib
- bib/surveyharmonization.bib
- bib/statisticalmethodology.bib
---

Our paper presents a work-in-progress which aims to create a pan-European music data PPP, the European Music Observatory, and a fully-fledged Slovak music data space as a national pilot program. In the context of transparency in curation, we take a comprehensive view, because we want to create registers that are unbiased or which have known and accounted for biases about the entire living and deceased music creator and music enterprise population, and their music works and sound recordings on both private and public data infrastructure.

We take a comprehensive view on data pooling [@mattioli_data-pooling_2017] because we want to connect privately-held data infrastructure (in the case of music, global rights management data infrastructure or streaming infrastructure) and public data infrastructure (cultural statistical production processes, music libraries and music heritage. organisations' data.) This corresponds to the new *European data strategy* and the various regulatory novelties and innovations in business-to-government and government-to-business data exchange and provides a vast canvas for curators and data stewards; in fact, we believe that we are providing an empirical pilot that can test the ideas presented by the *High-Level Expert Group on Business-to-Government Data Sharing* [@hleg_towards_b2g_data_2020]. On the flip side, our approach supports very wide findability, access, and interoperability or reuse; however, with an unusually high number of institutional, economic or legal barriers to actionable access and connection. We increase the transparency for human or algorithmic curators and provide a sandbox for testing novel legal instruments (both for higher data protection and unknown data connections) that had not been used in the cultural domain before.

## Background

`Open Music Europe` aims to provide a research data management and DMP supported with a software ecosystem that helps to fill the "data gaps" identified by 150 music stakeholders [@openmuse_2023]. In this regard, we are following the *Feasibility study for the establishment of a European Music Observatory : final report* [@emo_feasibility_2020], which identified numerous "data gaps" relevant for the European music economy, for measuring the diversity and circulation of European music, its sustainability, and provide data for music innovation.

For curation, our starting point is to understand why radio curators in Slovakia are failing to find relevant local content to fill their legal requirements for local content, i.e., broadcasting "Slovak" music. Such local content requirements are known in at least 80 jurisdictions, and they are facing policy challenges as human curators are increasingly changed to algorithmic curators. Digital music streaming is slowly overtaking radio broadcasting in access to recorded music, and it is dominantly algorithmically curated---most listeners are following music recommendation systems. Festival and radio editors are also increasingly relying on algorithmic help in their curatorial processes. In 2020, we created the *Feasibility Study On Promoting Slovak Music In Slovakia & Abroad*, which defined the *Slovak Comprehensive Music Database* as a shared resource [@antal_promoting_slovak_2020] to monitor local content guidelines, to test algorithmic biases in music curation, to assign blame for the significant prevalence of lateness in royalty payout or "cold start" and invisibility for Slovak creators on global music infrastructure. In 2023, we started the development of this database that will eventually lead to a Slovak music data space. We will present here the methodology of this work and the various public and institutional-level data policies that can be empirically tested with our pilot project. This work follows up on a comprehensive mapping and presentation of data in the entire Slovak and (separately) the Hungarian music sector [@antal_growth_2017; @antal_slovenskom_hudobnom_2019_en].

Most of our piloting takes place in Slovakia. To achieve our ambitious goal, our research and innovation project signed a memorandum of understanding with the Cultural Ministry of the Slovak Republic, the Institute of Cultural Policy, and initiated a collaboration with all relevant music institutions, libraries, businesses in the country, and the national statistical authority [@open_music_europe_sk_mou_2023]. We believe that this may create the basis for a most comprehensive data pooling public private partnership in culture.

## Methodology

Our methodology connects four guidelines well-supported by international standards and protocols: GSIM and the tidy data principle, FAIR and OPA. We take a broad, top-down approach inspired by the production processes of statistics. Statistical processing provides well-regulated procedures and results in two essential products: registers and summary statistics.

Our work is connecting four different guidelines, which are not standards or protocols, but which are well supported by them: GSIM from statistical innovation, FAIR from open science, OPA from open policy analysis, and the tidy data principle, which is inspired the renewal of the open source R statistical environment via tidyverse. While we offer to develop a solution in the R language, the research data management principles that we develop can be easily replicated in more general languages used for data science, for example, in Python or C++. Our aim is to support individual researchers or small groups to work with our data space without reliance to extensive data or knowledge engineering resources to support them in their workplaces.

The central concept that we take from statistical innovation is the creation of a harmonised *Slovak Music Register* and the *Slovak Music Business Register satellite*.

"A register aims to be a complete list of the objects in a specific group of objects or population." [@anders_register-based_2007] A *statistical register* is a continuously or regularly updated set of objects for a given population. It contains information on the identification and accessibility of population units as well as other attributes which support the surveying process of the population. It serves as a constantly updated list of potential data sources: people (muisc creators or performers) or enterprises (music labels, for-profit and social enterprise concert halls), for example, who may be invited to a sample survey or a census. The statistical register is both a coordination tool for data collection (everybody is found who should provide data), and an important data quality management tool (we know if somebody was not found, how it will distort our resulting datasets.)

The *register-statistical processing* includes various procedures to edit and code data, handle missing observations, etc., which are necessary to transform an administrative register that was initially not created for statistical data collection (for example, a register of music authors or producers of sound recordings which is intended for copyright management). We intend to connect this collaborative, public-private register with a structural business register satellite according to these guidelines to create an unambiguous data coordination tool among already harmonised state resources--such as the state registry of companies that includes commercial and non-commercial music organisations, or the population of living artists, following the new, relevant UN/EU statistical guidelines on experimental statistics and using privately-held data [@ess_position_privately_held_2017; @un_sbr_guidelines_2020, @eurostat_sbr_manual_2021].

Music registers, for example, allow us to have a comprehensive and unbiased view of music creators, music works or sound recordings, or their financial, environmental, or social data. Statistical aggregation and analysis can allow human curators and researchers to detect their potential biases if incomplete. Starting with a statistically sound register of music creators and their works is essential to assign blame for gender or ethnic biases of algorithmic curators, which are prevalent in music. For human curators or researchers, providing a statistically sound overview of the gender ratio of active composers or performers who meet any success criteria on stage can help the curation of more inclusive and more gender-balanced festivals or radio programs (a crucial current policy goal in music), or to meet the diversity of local content guidelines of public or commercial broadcasters. Registers with appropriate metadata are the best starting point for data stewards to design machine-actionable or human-curated research data management plans.

We are starting with creating a data coordination tool, i.e. the private and the parallel official (government) statistical register, because we want to make a well-regulated and quality-controlled connection [@european_statistics_code_of_practice_2017; @ESS_QAF_2019] between privately held data and government data. This way, we want to stress-test some novel policies introduced by the European Union in recent years.

One important stated goal of the European data strategy and the novel data governance and statistical regulation of the European Union is to foster data pooling in public-private partnerships. The same goal appears in the ex ante analysis of the European Collaborative Cloud for Cultural Heritage (ECCCH), too, but with a very public-centric view [@eccch_ex_ante_2022]. For this purpose, we want to critically review both the plans of the new data cloud and various earlier data collection plans, such as the European Audiovisual Observatory or the planned music observatory. The data gap analysis for the music industry reveals that the data, which would be desirable for curation, data stewardship or evidence-based policies, is almost hidden in plain sight.

If we make a quick search for recorded music in Europeana Music Art/activity of creating art using sound, brings up only 14,252 cultural objects. This equals roughly the number of cultural objects made available on Spotify every single day. In 2022, 213,000 artist, new creators, performers of authentic folk or classical music, and many others made at least ten new recordings available---with dozens of features that enable AI-driven algorithmic recommenders to seek audience for them globally from the day of release--, resulting on a growth of more than 2 million available music recordings. These recording can be found, enjoyed, listened to legally and even free, if the user is willing to listen to commercials, too. CISAC's global database, which is a shared creation of 225 creator societies in 116 countries in the private sector, contains information with pristine metadata about 52 million music works identified with the ISO 15707:2001 standard International Standard Work Code. These societies hold a sound recording, and in many cases, machine-readable or only human readable notation of the music work in copy. Less than 0.01% of them is even referenced in Europeana, and that aims to be an interoperable aggregator unbrella of European cultural heritage. The ex ante analysis of the ECCCH does not even contain the word "music".

GSIM is a reference framework of internationally agreed definitions, attributes and relationships that describe the pieces of information that are used in the production of official statistics (information objects). It creates a shared vocabulary between the SDMX and DDI to support standardised statistical production, including data pipelines. SDMX stands for the Statistical Data and Metadata eXchange: it is an international initiative that aims at standardising and modernising ("industrialising") the mechanisms and processes for the exchange of statistical data and metadata among international organisations and their member countries. SDMX has an ISO standard that is well harmonised with W3C linked open data vocabularies. The Data Documentation Initiative (DDI) is an international standard for describing the data produced by surveys and other observational methods in the social, behavioural, economic, and health sciences. Last, but not least, the tidy data principle connects some fundamental principles of computer science with statistics. It is widely used in the recent development of the R language itself, but as a principle, it is applicable for any computer language used for a programmatic work with tabular data, including most business ledgers, accounts, books, or institutional registers.

The creation of registers is a necessary but not sufficient first step for more transparent curation. While it dramatically increases findability, it cannot increase accessibility and interoperability, or usability, without further work. The statistical work paves the way for more comprehensive registers, which can be the foundations of better name spaces, catalogues. For music curators and data stewards, of course, access to digital cultural objects (music notation, lyrics, sound recordings) or data on music is the real aim. In this regard we want to reconcile our registers with the new Polifonia Music Meta ontology [@de_berardinis_polifonia_2023], which is a further development of previous ontologies used in classical music, popular music and Wikidata.

For bigger scientific and policy impact, we are following two further guidelines, FAIR and OPA (Open Policy Analysis Guidelines). These are, again, not standards or protocols either, FAIR is widely accepted in open science, and it is mandatory to apply some elements of this guidelines in every EU-funded research. OPA is a newer known standard that aims to apply transparency and reproducibility guidelines of social sciences (covered by FAIR) for public policy analysis [@OPA_framework_2020], thus making policy analysis evidence-driven and interoperable with open science.

## Policy and Impact

We aim to achieve a high policy impact on both the institutional level, which is relevant for most curators and data stewards and public policy. By connecting the institutional registers of music libraries and the Slovak Music Information Center on the one hand (public institutions in the GLAM sector) and music work/recordings registers and represented artist registers of collective and individual rights management organisations, we pave the way to make microdata or nano-level data (such a data beyond statistical subject level, for example, data of music royalty accounts) directly usable as a "privately held administrative data source" for experimental statistical production. We hope to provide the datasets and eventually statistical indicators and benchmarks for the sectorial Stratégia kultúry a kreatívneho priemyslu Slovenskej republiky 2030 [@slovak_cci_strategy_2023]---henceforth: Slovak CCI Strategy, the Slovakia's Vision and Development Strategy 2030 - a long-term strategy for sustainable development [@slovak_sdg_strategy_2020]---henceforth: Slovak Strategic SDGs, which has significant cultural elements, and the 2030 Digital Transformation Strategy for Slovakia [@2030_digital_transformation_slovakia_en_2019; @2030_digital_transformation_slovakia_sk_2019]--henceforth: Slovak Digitisation Strategy. Throughout the project, we will follow the Eurostat guidelines on creating new indicators [@eurostat_harmonised_indicators_1_2014; @eurostat_harmonised_indicators_2_2017; @eurostat_harmonised_indicators_3_2017].

Accessing directly collectively managed work registers or royalty accounts provides far more timely and precise view on the corporate or private income of the music sector, or the diversity of music used than annual surveys sent to music labels, concert promoters or musicians. Because we apply GSIM as a guideline, and SMDX and DDI as metadata standards to pave the way for quality-controlled data processes, we also clear the way for far more inclusive institutional curation or data stewardship policies that can control various biases better.

We take a comprehensive view on data pooling because we want to connect privately-held data infrastructure (in the case of music, global rights management data infrastructure or streaming infrastructure) and public data infrastructure (cultural statistical production processes, music libraries and music heritage. organisations' data.) This corresponds to the new European data strategy and the various regulatory novelties and innovations in business-to-government and government-to-business data exchange and provides a vast canvas for curators and data stewards. On the flip side, our approach supports very wide findability, access, and interoperability or reuse; however, with an unusually high number of institutional, economic or legal barriers to actionable access and connection. We increase the transparency for human or algorithmic curators and provide a sandbox for testing novel legal instruments (both for higher data protection and unknown data connections) that had not been used in the cultural domain before.

Our methodology connects four guidelines well-supported by international standards and protocols: GSIM and the tidy data principle, FAIR and OPA. We take a broad, top-down approach inspired by the production processes of statistics. Statistical processing provides well-regulated procedures and results in two essential products: registers and summary statistics.

Music registers, for example, allow us to have a comprehensive and unbiased view of music creators, music works or sound recordings, or their financial, environmental or social data. Statistical aggregation and analysis can allow human curators and researchers to detect their potential biases if incomplete. One of our initial starting points was the *Feasibility Study On Promoting Slovak Music In Slovakia & Abroad*, which set the requirements needed to to assign blame for gender or ethnic biases of algorithmic curators.

Starting with a statistically sound register of music creators and their works is essential for more transparent and better curation. For human curators or researchers, providing a statistically sound overview of the gender ratio of active composers or performers who meet any success criteria on stage can help the curation of more inclusive and more gender-balanced festivals or radio programs (a crucial current policy goal in music), or to meet the diversity of local content guidelines of public or commercial broadcasters. Registers with appropriate metadata are the best starting point for data stewards to design machine-actionable or human-curated research data management plans.

While our project is limited to music, we believe that we can provide an early empirical testing ground for novel data policies and regulations: both intended for increased personal data protection and for the pooling of private and public data.

## Acknowledgements

Funded by the European Union under Grant No. 101095295. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Commission's Citizens, Equality, Rights and Values Programme. Neither the European Union nor the granting authority can be held responsible for them.

## References
