---
title: "Lightning Talk"
format: 
   html: default
   gfm: default 
editor: visual
---

```{=html}
<!-- Lighting talks are an opportunity to showcase work in progress or completed projects that you believe offers insights or practical lessons that advance digital curation research or practice. Treat IDCC24 as a stage where you can make your work known and potentially recruit partners to collaborate with.

You should submit as a 1-page proposal (approximately 500 words) that describes the work you would like to present, and its relevance to the topic of the conference. Please fill out the name, postal address, and email address of the corresponding author in the footer below and add the author information using the table above. Each cell should contain one author name and one affiliation. Please delete unused rows or copy and paste rows to include more authors.

If your proposal is accepted, you will be invited to give a 10-minute presentation at IDCC. For further details, please see: https://www.dcc.ac.uk/events/18th-international-digital-curation-conference -->
```
## Abstract

Open Music Europe is a Horizon Europe project that aims to build a working prototype of the planned European Music Observatory.

The EU, UN, or other international bodies have recognised or initiated at least 60 data observatories that carry out long-term data collection on various domains; we have not found any good policies or practices on how to place these observatories on data infrastructures that are interoperable towards open science and open government. We are creating a data management and governance model and a working MVP that coordinates data collection and statistical data production among scientific, private and official statistical actors.

Our most crucial pilot project wants to showcase a best practice for using privately-held data, i.e., data of music organisations and surveys carried out by scientific and business actors, to improve the quality of government statistics. We show how the guidelines on using private data as an 'administrative data source' and an ex-ante harmonisation of governmental surveys with open scientific surveys can result in high-quality datasets that fully complement the pre-existing official statistical products and commercial products.

As a coordination tool, we started developing a Data Management Plan to increase transparency from the outset. Apart from applying Horizon Europe's OpenAIRE recommendations and FAIR requirements, we use the Open Policy Analysis Guidelines to bring open science transparency into the less standardised policy analysis area. We implement this following various UN/EU Guidelines on statistical production, creating a three-way reconciliation and interoperability, i.e., scientific research, public policy design and official statistics.

Our work contributes to sharing outputs earlier using Open Research platforms because we are building a framework supported by research automation that integrates open science, business, and official governmental data. We develop a software ecosystem complementing the R statistical environment and language, the lingua franca of official and scientific statistics, to make the data curation, pre-processing, processing, and eventual quality-controlled statistical data release open, transparent, and much timelier.

Our project follows an open collaboration framework that we design so that private music NGOs and enterprises, statistical offices and open science research groups can work together on the curation and design, production and release and use of data assets in the cultural domain. By opening the statistical infrastructure with our open-source production code and implementing the statistical data and metadata exchange standards simultaneously with other metadata standards and standardisation techniques like ex-ante and retrospective survey harmonisation, we hope to combine them in novel ways like never before while making them available sooner. Our showcase product will be a twin, linked open data resource: the Slovak Comprehensive Music Database. It will connect in unprecedented detail information about musical works and their sound recordings and notations in music libraries, heritage organisations and individual and collective rights management organisations. We will derive the Slovak Music Industry Registry from this linked open resource that we will convert into a structural business register satellite as an interface between the privately-held data of music management and music heritage institutions and the national/satellite account system of the Slovak Republic, particularly the Slovak Cultural and Creative Satellite Accounts.

## Lightning talks

::: callout-note
Digital curation involves maintaining, preserving and adding value to digital research data throughout its lifecycle.

The active management of research data reduces threats to their long-term research value and mitigates the risk of digital obsolescence. Meanwhile, curated data in trusted digital repositories may be shared among the wider UK research community.

As well as reducing duplication of effort in research data creation, curation enhances the long-term value of existing data by making it available for further high quality research.
:::

Open Music Europe is a Horizon Europe project that aims to build a working prototype of the planned European Music Observatory. When we are working out how to fill the data gaps for the music research, evidence-based public policies, and the needs of the European music enterprises, we are following a the dataspace model and some novel innovations in the regulation of public-private data fusion. Our company also won the EIT CCI Breakthrough Lab's award and we are building a similar sustainable film production dataspace.

## Problem statement

Our music and film dataspaces aim for a data stewardship that crosses boundaries between government administration data, public research and memory data, and private data. Such data coordination has many challenges, but the benefits are obvious.

Last weekend, Europeana had 12,416 sound recordings that you could use without restrictions and altogether, 206,280 music sound recordings were made available over ten years. The same amount is made available with excellent service support and free listening licensing options on Spotify in every 2 days. If we placed the music we handle in Slovakia alone on Europeana in our project, we would double Europeana's music collection, even though the Slovak Republic accounts for only 1% of the European Union's population and music creation.

Generally, I believe that there is a lot to gain from connecting public and private data infrastructures and creating data spaces that form a PPP. This is particularly appealing in the case of books, journals, literary and music works, audiovisual material, architecture plans, and photographs because these carriers of knowledge have a place in public memory institutions, but due to the highly long copyright protection terms worldwide, they have a private, rights management data infrastructure, too.

Not only has the private sector digitized practically all books, cinematic works, music, music sheets, and billions of photographs, but because the current copyright protection term is running up to 150 years--70 years after the death of the last surviving rightsholder, and royalties must be paid to the correct person or heir annually, or even quarterly or monthly, their databases have timely metadata. Why should not heritage organisations use commercial platforms when they make their relevant content available in a licensed and easily accessible way? What if data curators in science and heritage organisations could get access to such an improvement to their namespaces?

Or, to go one step further, and dig into the digital storage of archives, we find that most of the images, sound recordings and audiovisual content that cannot be shown to the public usually has a right management data problem (the names and availability of rightsholder information is out of date) or the necessary public performance licenses are missing. Could we obtain the name and license holder data for long out-of-commerce films from a data space and allow their on-site screening or viewing on the web? We have these use cases in mind when building a music dataspace in Slovakia and a film dataspace in Hungary, both to be scaled up to the EU level.

## Dataspace with private, public, and state data

Our work is technically challenging because we work with multi-modal data: we have datasets, texts, sound recordings and audiovisual files. In 2024, we will only work with textual information. For example, we want to ensure that people can find any Slovak music works in a public data space, listen to a recorded fixation of the work on a licensed streaming platform, and get information about the availability of the music scores in public libraries for lending, or in webshops for buying.

In 2025, we want to go a step further. We want to build applications, such as our Listen Local application family, which allows radios to enrich, according to broadcasting law, their radio playlists with mandatory local content. Or to help educators, under parental supervision, take the playlists of teenagers in a music education setting and modify their recommendations with music that fits into classroom pedagogy based on the national music discovery curriculum. For such an application, we will have to go far beyond the simple metrics of a sound recording, like the duration of the recording in milliseconds; we want to record key, normalised chord progression, instrumentalisation, and dynamics of the sound recordings.

## Technical solution

For a first step of data coordination, we set up -- in cooperation with Wikipedia -- a Wikibase instance that will remain private and will negotiate. Titles, headings, and descriptions among the Slovak National Library, music libraries, the Music Centre Slovakia and the rights management organisation SOZA. The aim is to come to a mutual understanding of their database contents and, whenever possible, to create links to authoritative global identifiers, such as VIAF for persons, the CISAC global database for works, and the ISMN for their sheet notation and ISRC code of their various recorded fixations. Using Wikibase will allow us to synchronize knowledge with Wikidata, of course, after GDPR and rights clearance, and whenever global identifiers are missing, to use QID as a global identifier or to facilitate obtaining, for example, a missing ISWC or VIAF identifier for a previously unpublished music work or arrangement, or a new person.

The second step of data coordination is to ensure that the data partners ensure that all instances of important objects, such as persons as creators or performers, work, are placed under global authority control. Using, when possible, the Wikidata QID as one global ID for coordination, the national library will ensure that all name headings are correctly placed on VIAF, or SOZA will ensure that all discovered and unpublished new music works get a globally unique and standard ISWC identifier and placed into the CISAC global database.

For the research and data curation community, our value proposition is that we will describe both private and public databases, repositories in RDF utilising mainly the CIDOC-CRM model for heritage purposes, the Polifonia Ontology Network for musicology research and rights management, and the Europeana Data Model, and the DCAT-AP application profile of the EU Open Data Portal for findability.

## Legal coordination

Our work's novelty and greatest challenge so far is the management of somewhat different data jurisdictions. The most apparent difference between these three groups is how they do not apply GDPR.

-   [x] Statistical agencies do not apply GDPR but higher standards, and we must use novel data coordination and legal instruments for coordinating statistical registers and frames among state and privately-held data.

-   [x] Heritage organisations and libraries are often exempted to some degree from using GDPR. For example, they can put the names of many authors into a public library catalogue.

-   [x] Rights management organisations utilise highly detailed personal data about authors concerning their works but must use such data only for rights management, and they fall under very strict GDPR data protection rules.

Take the example of data exchange with statistical agencies. They have unrivalled access to create census-like information (for example, they know of every person who makes music in the Slovak Republic or every enterprise that releases their recordings). Yet rights management organisations have far more timely and accurate information about royalty income than statisticians, who rely on imprecise surveying instead of accessing data from the financial ledgers of music royalty accounts.

Or, rights management organisations have a more timely namespace because they must ensure that persons who change names after marriage or divorce or legal entitlement changes like the inheritance of economic rights are reflected in their systems for annual, quarterly, or even monthly royalty payments. This would be a boon for heritage cataloguing. However, heritage organisations have better data for negative rights clearance, for example, to definitively conclude that a work is in the public domain and needs no rights management.

While data coordination, cross-pollination, data enrichment, and improvement appear to be win-win-win, crossing such institutional and data jurisdiction boundaries is a very novel use case. For example, while the UN and EU statistical guidelines and regulations allow the use of privately held data for statistical purposes, we have only found examples like the use of cash register or credit card data and smart energy metering data in homes for household spending and energy statistics. Coordinating statistical and rights management or heritage registers and using royalty accounting data to establish the number of concerts and viewers and the aggregate amount spent on concert tickets have not been carried out to our knowledge anywhere in the world in a comprehensive, government statistical program.

Therefore, during this coming spring, we do not see our role only as getting consent from musicians or statisticians. To avoid later legal or ethical challenges, we start a consultative public relations campaign to educate data stakeholders about the state of play and the unprecedented technical capabilities so that they can genuinely balance their data interests and make informed consents about the use of their data.
