---
title: "Lightning Talk"
format: 
   html: default
   gfm: default 
editor: visual
---

<!-- Lighting talks are an opportunity to showcase work in progress or completed projects that you believe offers insights or practical lessons that advance digital curation research or practice. Treat IDCC24 as a stage where you can make your work known and potentially recruit partners to collaborate with.

You should submit as a 1-page proposal (approximately 500 words) that describes the work you would like to present, and its relevance to the topic of the conference. Please fill out the name, postal address, and email address of the corresponding author in the footer below and add the author information using the table above. Each cell should contain one author name and one affiliation. Please delete unused rows or copy and paste rows to include more authors.

If your proposal is accepted, you will be invited to give a 10-minute presentation at IDCC. For further details, please see: https://www.dcc.ac.uk/events/18th-international-digital-curation-conference -->

Open Music Europe is a Horizon Europe project that aims to build a working prototype of the planned European Music Observatory. 

The EU, UN, or other international bodies have recognised or initiated at least 60 data observatories that carry out long-term data collection on various domains; we have not found any good policies or practices on how to place these observatories on data infrastructures that are interoperable towards open science and open government. We are creating a data management and governance model and a working MVP that coordinates data collection and statistical data production among scientific, private and official statistical actors.

Our most crucial pilot project wants to showcase a best practice for using privately-held data, i.e., data of music organisations and surveys carried out by scientific and business actors, to improve the quality of government statistics. We show how the guidelines on using private data as an 'administrative data source' and an ex-ante harmonisation of governmental surveys with open scientific surveys can result in high-quality datasets that fully complement the pre-existing official statistical products and commercial products.

As a coordination tool, we started developing a Data Management Plan to increase transparency from the outset. Apart from applying Horizon Europe's OpenAIRE recommendations and FAIR requirements, we use the Open Policy Analysis Guidelines to bring open science transparency into the less standardised policy analysis area. We implement this following various UN/EU Guidelines on statistical production, creating a three-way reconciliation and interoperability, i.e., scientific research, public policy design and official statistics.

Our work contributes to sharing outputs earlier using Open Research platforms because we are building a framework supported by research automation that integrates open science, business, and official governmental data. We develop a software ecosystem complementing the R statistical environment and language, the lingua franca of official and scientific statistics, to make the data curation, pre-processing, processing, and eventual quality-controlled statistical data release open, transparent, and much timelier.

Our project follows an open collaboration framework that we design so that private music NGOs and enterprises, statistical offices and open science research groups can work together on the curation and design, production and release and use of data assets in the cultural domain. By opening the statistical infrastructure with our open-source production code and implementing the statistical data and metadata exchange standards simultaneously with other metadata standards and standardisation techniques like ex-ante and retrospective survey harmonisation, we hope to combine them in novel ways like never before while making them available sooner. Our showcase product will be a twin, linked open data resource: the Slovak Comprehensive Music Database. It will connect in unprecedented detail information about musical works and their sound recordings and notations in music libraries, heritage organisations and individual and collective rights management organisations. We will derive the Slovak Music Industry Registry from this linked open resource that we will convert into a structural business register satellite as an interface between the privately-held data of music management and music heritage institutions and the national/satellite account system of the Slovak Republic, particularly the Slovak Cultural and Creative Satellite Accounts.

